### ISSUE TITLE
Lineplot

### ISSUE THREAD

**Issue by jmueller95** [wilhelm-lab/biowc-core#22]
Ideas for extensions:
- [x] Guided sliding along the line
![grafik](https://user-images.githubusercontent.com/22984706/212738059-5d71a946-3ed7-48e8-9058-be84b38ba264.png)

**Comment by katharily** [comment]
- [x] axis labels
- [ ] link function - dots
- [x] download button
- [x] lines while sliding on function
- [ ] Title on top
- [x] Allow user to NOT connect dots with line
